version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx:1.0
    volumes:
      - wordpress_vol:/var/www/html
    build: requirements/nginx
    ports:
      - "5455:5455"
    restart: on-failure

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/nfs/homes/mbocquel/c_cursus/webserv_common_git/docker_nginx/sites'